repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]

      - id: unittests
        name: run unit tests
        entry: venv/bin/python -m unittest
        language: system
        pass_filenames: false
        args: ["discover"]